
# Workflow disparado por push para branches que começam com "feature/"
on:
    push:
        branches: "feature/main"
 
# env é uma palavra-chave que define variáveis de ambiente que podem ser usadas em todo o workflow       
env:
  IMAGE_NAME: simple-api-java
  AZURE_WEBAPP_NAME: simple-api-java
 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
 
        -   name: Setup Java SDK 
            uses: actions/setup-java@v4 
            with: 
              distribution: 'temurin'  
              java-version: '21'
        -
            name: Login to Docker Hub
            # Ação para fazer login no Docker Hub
            uses: docker/login-action@v3
            # Configuração do login no Docker Hub com as credenciais armazenadas no GitHub Secrets
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
            name: Build 
            # Ação para construir e empurrar imagens Docker para um registro de contêiner
            uses: docker/build-push-action@v6 
            with: 
                # push: true para empurrar a imagem para o Docker Hub
                push: true
                # tags: para marcar a imagem com o nome do repositório e a tag latest
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    # Deploy job para implantar a aplicação no Azure Web App
    deploy:
        runs-on: ubuntu-latest
        # Dependências do job deploy: build
        needs: build
        steps:
        - 
            name: Deploy to Azure Web App
            # id é uma palavra-chave que define um identificador exclusivo para o job
            id: deploy-to-webapp
            # Ação para implantar aplicativos em um Azure Web App
            uses: azure/webapps-deploy@v2
            # Configuração da ação para implantar o aplicativo no Azure Web App com as credenciais armazenadas no GitHub Secrets
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
